article about pipeline mode
psycopg/psycopg-website pull request #19
Opened 2022-10-12 14:41 UTC by dlax

@dvarrazzo, as discussed, this is a reuse of the [article on dalibo's blog](https://blog.dalibo.com/2022/09/19/psycopg-pipeline-mode.html), with (minor) changes in the second commit. I think we can change more things if appropriate, let me know.

2022-10-16 23:35 UTC, dvarrazzo requested changes
Just some minor cleanups. Great article :)

2022-10-16 23:35 UTC, dvarrazzo commented on content/articles/psycopg3-pipeline-mode/contents.lr
> +   F   385 Bind     "" "_pg3_3" 3 1 1 1 3 338 '\x00\xffffffa5\x00\xffffffa4\x00\x00\x00\x00\x00\x06\x14D\x08k\x0c\xffffffbe\x04\xffffffd9\x1e\xffffffb2\x05\xffffffbe$\xffffffcf\x1e\xffffffa9\x152\x1f
Maybe these strings can be shortened in the examples?

2022-10-16 23:35 UTC, dvarrazzo commented on content/articles/psycopg3-pipeline-mode/contents.lr
> +Result Processing and Query Dispatch” states: > The client application
You can make a block quote in reST by indenting. So, untested:

```
Query Dispatch” states:

    The client application should generally maintain a queue of work remaining
    to be dispatched and a queue of work that has been dispatched but not yet
    had its
    ...
```

2022-10-16 23:35 UTC, dvarrazzo commented on content/articles/psycopg3-pipeline-mode/contents.lr
> +As often with PostgreSQL, everything is there. But this paragraph is
```suggestion
As often with PostgreSQL, everything is there, although this paragraph is
```

2022-10-17 14:46 UTC, dlax commented on content/articles/psycopg3-pipeline-mode/contents.lr
> +(``n!, n<1000``). Maybe the application could make use of batch inserts
Indeed, I have dropped this as it's not very meaningful after all.

2022-10-17 14:47 UTC, dlax commented
The publication date is passed (last week); should I update it or leave it to you?

2024-03-08 09:27 UTC, dlax commented
Seems we forgot about this[^1]; probably not worth any more or too late.

[^1]: I'm cleaning up old PRs

2024-05-03 07:29 UTC, dlax commented
@dvarrazzo, as discussed, let's try again to republish this article to psycopg's blog; whenever you have time :)

2024-05-03 07:30 UTC, dlax commented on content/articles/psycopg3-pipeline-mode/contents.lr
> +pub_date: 2022-10-14
To be updated before publication.

2024-05-08 11:30 UTC, dvarrazzo commented on content/articles/psycopg3-pipeline-mode/contents.lr
> +pub_date: 2022-10-14
Set it to today

2024-05-08 11:31 UTC, merged

2024-05-08 11:42 UTC, dvarrazzo commented
The article has been published, thank you very much :)

If it's ok I'll mention it on some social media post. Of course feel free to do the same!

2024-05-13 07:35 UTC, dlax commented
> The article has been published, thank you very much :)

Great!

> If it's ok I'll mention it on some social media post.

Yes, of course, no problem.